language: go

go:
  - master

install:
  - go get github.com/spf13/hugo

script:
  - hugo -t ananke

deploy:
  local_dir: public # Default static site output dir for Hugo
  repo: MonashDataFluency/MonashDataFluency.github.io # This is the slug of the repo you want to deploy your site to
  target_branch: master # GitHub pages branch to deploy to (in other cases it can be gh-pages)
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # This is the authentication which you will setup in the next step in travis-ci dashboard
  email: ajperry@pansapiens.com
  name: "Andrew Perry"
  on:
    branch: master
