language: go

go:
  # - master
  - release-branch.go1.10

install:
  - go get github.com/magefile/mage
  - go get -d github.com/gohugoio/hugo
  - cd ${GOPATH:-$HOME/go}/src/github.com/gohugoio/hugo
  - mage vendor
  - mage install
  # Or just grab the binaries
  # - wget https://github.com/gohugoio/hugo/releases/download/v0.41/hugo_0.41_Linux-64bit.deb
  # - dpkg -i https://github.com/gohugoio/hugo/releases/download/v0.41/hugo_0.41_Linux-64bit.deb

script:
  - hugo -t ananke

deploy:
  local_dir: public # Default static site output dir for Hugo
  repo: MonashDataFluency/MonashDataFluency.github.io # This is the slug of the repo you want to deploy your site to
  target_branch: master # GitHub pages branch to deploy to (in other cases it can be gh-pages)
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # This is the authentication which you will setup in the next step in travis-ci dashboard
  email: ajperry@pansapiens.com
  name: "Andrew Perry"
  on:
    branch: master
