baseURL = "https://MonashDataFluency.github.io/"
languageCode = "en-us"
title = "Monash Data Fluency"
theme = "ananke"
copyright = "Content released under a Creative Commons Attribution 4.0 International license (CC BY 4.0)."
googleAnalytics = ""

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  github = "https://github.com/MonashDataFluency"
  twitter = "https://twitter.com/ResDatFlu"
  slack = "https://datafluency.slack.com"
  featured_image = "/images/banner.jpg"
  recent_posts_number = 3

  # any Section listed here has recent posts listed on the front page
  mainSections = []

  show_title_in_navigation = false

  # list Sections here (by filename minus .md) that you want to exclude from the front page navigation
  hide_sections_in_main_menu =  ["workshops"]

[menu]

[[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"

[[menu.main]]
    name = "Events"
    weight = 2
    identifier = "events"
    url = "/events"

[[menu.main]]
    name = "Resources"
    weight = 3
    identifier = "resources"
    url = "/resources"

#[[menu.main]]
#    name = "Challenges"
#    weight = 4
#    identifier = "challenges"
#    url = "/challenges"

[[menu.main]]
    name = "Contact"
    weight = 5
    identifier = "contact"
    url = "/contact"

[[menu.main]]
    name = "About"
    weight = 6
    identifier = "about"
    url = "/about"
